jobs:
  update-durations:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Update package list
      run: sudo apt-get update

    - name: Install dependencies
      run: |
        sudo apt-get install -y --fix-missing <your-packages-here>
